const categories = [
    "None",
    "Art",
    "Biography",
    "Business",
    "Classics",
    "Comics",
    "Contemporary",
    "Cookbooks",
    "Crime",
    "Fantasy",
    "Fiction",
    "LGBTQ+",
    "Graphic Novels",
    "History",
    "Horror",
    "Humor and Comedy",
    "Magic",
    "Manga",
    "Memoir",
    "Music",
    "Mystery",
    "Nonfiction",
    "Paranormal",
    "Philosophy",
    "Poetry",
    "Politics",
    "Psychology",
    "Religion",
    "Romance",
    "Science",
    "Science Fiction",
    "Self Help",
    "Short Stories",
    "Society",
    "Spirituality",
    "Sports",
    "Thriller",
    "Travel",
    "Young Adult"
];

module.exports = categories;